# Project information
site_name: Пишем Telegram-ботов на Python (v2)
site_description: Учебник по разработке ботов для Telegram на языке Python
site_author: MasterGroosha
site_url: https://mastergroosha.github.io/telegram-tutorial-2
docs_dir: book_src
site_dir: docs

# Repository
repo_name: MasterGroosha/telegram-tutorial-2
repo_url: https://github.com/MasterGroosha/telegram-tutorial-2
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2021 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: ru
  palette:
    primary: teal
    accent: teal
    scheme: preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/TsftDfnevFLQS1ts
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MasterGroosha/telegram-tutorial-2
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/groosha/telegram-tutorial-2
      name: Gitlab

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - toc:
      permalink: true

nav:
  - 'Введение': index.md
  - 'Знакомство с aiogram': quickstart.md
  - 'Работа с собщениями': messages.md
  - 'Кнопки': buttons.md
  - 'Конечные автоматы': fsm.md
  - 'Инлайн-режим': inline_mode.md


plugins:
  - search:
      lang:
        - en
        - ru


# Custom
nav_name: "Оглавление"
